---
  - name: Ensure dependencies are installed
    yum: name={{ item }} state=present
    with_items:
        - ftp
        - unzip
        - zlib-devel
        - bzip2-devel
        - openssl-devel
        - ncurses-devel
        - readline-devel
        - pcre-devel
        - curl-devel
        - sqlite-devel

  - name: Check if python is already installed
    stat: path=/usr/local/bin/python3.6
    register: python

  - name: Create application directory (owned by application_user)
    file:
        path: "{{ application_deploy_to }}"
        state: directory
        owner: "{{ application_user }}"
        group: "{{ application_group }}"

  - name: Download & unpack Python
    unarchive:
        src: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
        dest: "{{ application_deploy_to }}"
        remote_src: yes
        owner: "{{ application_user }}"
        group: "{{ application_user }}"
    when: not python.stat.exists

  - name: Configure, compile and install Python
    shell: cd "{{ application_deploy_to }}/Python-{{ python_version }}" && {{ item }}
    with_items:
        - ./configure --prefix=/usr/local
        - make
        - make altinstall
    when: not python.stat.exists

  - name: Create virtualenv and Install iPython
    pip:
        name: ipython
        virtualenv: "{{ application_deploy_to }}/{{ application_venv_name }}"
        virtualenv_command: /usr/local/bin/python3.6 -m venv
