---
  - name: Check if samtools already available
    stat:
        path: /usr/local/bin/samtools
    register: samtools

  - name: Download and unarchive Samtools-{{ samtools_version }}
    unarchive:
        src: "https://sourceforge.net/projects/samtools/files/samtools/1.2/samtools-{{ samtools_version }}.tar.bz2"
        dest: "{{ application_deploy_to }}"
        validate_certs: no
        remote_src: true
    when: not samtools.stat.exists

  - name: Compile and install Samtools-{{ samtools_version }}
    shell: cd "{{ application_deploy_to }}/samtools-{{ samtools_version }}" && {{ item }}
    with_items:
        - make
        - make install
    when: not samtools.stat.exists
